--====================================================================================================
--                                  10 registros para Sucursal
--====================================================================================================
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia La Paz','Hidalgo',31,3,'Lomas de Chapultepec','Baja California',+2086699526903);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia Santa Ana','Morelos',31,85,'Del Valle','Campeche',0654679203);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Lucas','Allende',56,33,'Polanco','Colima',+60951108371);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Pablo','Hidalgo',72,98,'Del Valle','Nuevo León',6604652896);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Rafael','Benito Juárez',94,5,'Satelite','Durango',+61717498215);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia del Sol','Allende',71,67,'San Pedro','San Luis Potosí',7057635231);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Pablo','Callejón del Beso',81,84,'Satelite','México',7018665323);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Lucas','Hidalgo',90,68,'Napoles','Oaxaca',+247821131524);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia del Sol','Galeana',54,11,'Cuajimalpa','Baja California',0027789450);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Miguel','Juárez',65,81,'Del Valle','Puebla',+322210547084);

--====================================================================================================
--                                  10 registros para Cliente
--====================================================================================================
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Nertie','Elnor','Utterson','2006-01-08','Carranza',30,89,'Bosques de Chapultepec','Baja California','Tarjeta');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Candy','Sketh','Baert','1949-12-28','Callejón del Beso',19,36,'La Paz','Durango','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Leland','Dovinson','McUre','2025-04-30','Gutiérrez',58,7,'Bosques de Chapultepec','Baja California','Tarjeta');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Eward','Braley','Simonite','1966-07-02','Morelos',33,80,'Los Pinos','Chiapas','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Erny','Rowler','Tures','1997-01-20','Carranza',44,2,'Valle Verde','Yucatán','Tarjeta');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Elspeth','Pooley','O''Bruen','1982-03-02','Calle de la Amargura',1,83,'Valle Verde','Chiapas','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Kevina','Casado','Albert','1972-11-27','Guerrero',93,1,'Santa Lucía','Aguascalientes','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Padraig','Broadist','Bielefeld','1951-10-28','Calle de la Amargura',48,23,'San Pedro','Tabasco','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Isaac','Alyonov','Reinbeck','2019-08-13','Calle de la Soledad',60,76,'La Paz','Tlaxcala','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Lynnea','Stocking','Siddaley','2018-05-31','Independencia',83,58,'Valle Verde','Tabasco','Efectivo');

--====================================================================================================
--                                  10 registros para Medico
--====================================================================================================
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('YDWV321202316','Leontyne','Goldthorp','Titterington','Callejón de la Condesa',90,84,'La Aurora','Sinaloa','Miercoles','23:06','07:06',61490098.63,2,'Colegio de Médicos y Cirujanos','9/6/2024',1000001,'6/20/1999');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('PFUB761101FQ6','Idette','Bealton','Swinn','González',75,81,'Villa de las Flores','Baja California','Sabado','14:57','22:57',2630099.63,5,'Instituto Nacional de Ciencias de la Salud','4/10/2023',1000002,'12/2/1998');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('IRQC461018365','Felicio','Hawkett','McQuillin','Morelos',56,12,'Las Palmas','Baja California','Jueves','6:05','14:05',13983963.91,2,'Hospital Universitario de Medicina','3/1/2029',1000003,'7/13/1991');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('DWSD450408078','Aloise','Champneys','Tranckle','Carranza',66,25,'Santa Cruz','Querétaro','Sabado','13:07','21:07',32525660.72,6,'Centro de Estudios Médicos Avanzados','2/7/2027',1000004,'8/2/1996');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('KFES640705YP8','Crysta','Spratley','Bourdel','Obregón',99,8,'Las Palmas','Durango','Domingo','8:18','16:18',24855994.01,10,'Escuela Superior de Ciencias de la Salud','8/19/2026',1000005,'9/1/1996');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('MHYY920601195','Philipa','Guitte','Cunnington','Zaragoza',46,66,'Valle Verde','Oaxaca','Jueves','2:26','10:26',79151894.1,3,'Instituto de Investigación Médica','9/22/2030',1000006,'4/5/1999');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('KRBZ750306M92','Arleen','Reding','Bilham','López Mateos',30,70,'Valle Verde','Baja California','Jueves','21:01','05:01',21738348.08,3,'Escuela de Medicina y Ciencias de la Salud','5/7/2028',1000007,'10/24/1990');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('ENUT4610231V5','Kip','Croy','Welburn','Obregón',68,96,'Los Pinos','Aguascalientes','Jueves','13:43','21:43',6783264.74,4,'Centro de Estudios Médicos Avanzados','8/28/2025',1000008,'4/26/1998');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('MBMO380825M20','Timoteo','Agg','Andreas','Allende',45,88,'San Miguel','Tamaulipas','Martes','20:51','04:51',4993929.69,4,'Instituto de Salud Pública','4/21/2023',1000009,'2/5/1996');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('OXMJ631222BH4','Chere','Martino','Drysdale','Revolución',25,31,'San Pedro','Puebla','Domingo','15:21','23:21',71631132.5,8,'Facultad de Medicina y Cirugía','2/6/2025',1000010,'10/30/2000');

--====================================================================================================
--                                  10 registros para Enfermero
--====================================================================================================
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('KDWS490405RC9','Jareb','Drage','Olanda','Benito Juárez',61,80,'El Rosario','El Rosario','Miercoles','16:13','00:13',45067793.16,2,'Cambio de Vendajes','false',1000001,'9/23/1991');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('XLBF860620H76','Marabel','Gowers','Pawellek','López Mateos',20,100,'Los Pinos','Bosques de Chapultepec','Jueves','13:04','21:04',63396757.72,7,'Cuidados Intensivos','true',1000002,'1/18/1995');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('XJCA211005B38','Lynnell','Parzis','Aizikowitz','Hidalgo',75,22,'Las Palmas','Bosques de Chapultepec','Domingo','2:54','10:54',60915296.25,5,'Aplicación de Inyecciones','false',1000003,'2/5/1992');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('PFRA800627T69','Charleen','Gotch','Nock','Callejón del Beso',69,49,'La Primavera','Valle Verde','Domingo','10:13','18:13',58581809.3,5,'Toma de Muestras de Sangre','true',1000004,'5/14/1998');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('VGMB840710277','Martguerita','Leppingwell','Kindon','Callejón del Beso',87,11,'Valle Verde','Santa Cruz','Lunes','18:05','02:05',84756127.66,10,'Retiro de Sonda','false',1000005,'8/11/1994');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('SJUY321021EU7','Hedvige','Vernon','Mathelin','López Mateos',44,94,'Valle Verde','La Joya','Domingo','14:00','22:00',80299719.89,8,'Atención Psiquiátrica','false',1000006,'8/4/1990');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('VIPU4907070U4','Tonya','Kairns','Cotty','Pino Suárez',18,28,'Las Palmas','Las Palmas','Martes','2:09','10:09',11379306.94,5,'Curación de Heridas','true',1000007,'3/4/1998');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('FLGM240702R38','Nomi','Hechlin','Norgan','Morelos',36,17,'El Paraíso','Los Pinos','Martes','8:48','16:48',35727340.01,5,'Control de Glucosa','false',1000008,'4/16/1992');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('KNJB701112J85','Vivi','Evequot','Gillan','Morelos',27,76,'La Primavera','Villa de las Flores','Jueves','6:11','14:11',36310423.78,7,'Monitoreo de Pacientes','false',1000009,'6/18/1994');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('UTCN211112313','Alene','Fullerd','Chatwood','Carranza',89,44,'La Aurora','Los Pinos','Miercoles','13:34','21:34',29349745.59,10,'Atención Pediátrica','true',1000010,'12/30/1991');


--====================================================================================================
--                                  8 registros para Ticket
--====================================================================================================
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-06-22','16:19','Presencial',1,6,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2024-01-19','2:26','Presencial',4,10,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2027-11-19','0:47','Presencial',8,6,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2028-01-15','9:00','Web',10,1,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2029-03-26','22:50','Web',3,10,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-09-08','10:26','Presencial',1,3,FALSE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-07-29','11:02','Web',8,1,FALSE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2030-09-25','10:34','Presencial',7,5,FALSE,TRUE);

--====================================================================================================
--                                  5 registros para CobrarConsulta
--====================================================================================================
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2024-01-18','2:00','Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',825.18,6,'MBMO380825M20',NULL,1);
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2012-07-29','18:59','Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',1029.04,10,'PFUB761101FQ6',NULL,2);
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2014-06-20','6:37','Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',1235.0,6,'OXMJ631222BH4','SJUY321021EU7',3);
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2023-09-26','15:28','Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',595.7,1,'IRQC461018365','VGMB840710277',4);
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2012-06-01','19:48','Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',708.68,10,'IRQC461018365','PFRA800627T69',5);
