--====================================================================================================
--                                  10 registros para Sucursal
--====================================================================================================
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia La Paz','Hidalgo',31,3,'Lomas de Chapultepec','Baja California',+2086699526903);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia Santa Ana','Morelos',31,85,'Del Valle','Campeche',0654679203);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Lucas','Allende',56,33,'Polanco','Colima',+60951108371);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Pablo','Hidalgo',72,98,'Del Valle','Nuevo León',6604652896);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Rafael','Benito Juárez',94,5,'Satelite','Durango',+61717498215);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia del Sol','Allende',71,67,'San Pedro','San Luis Potosí',7057635231);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Pablo','Callejón del Beso',81,84,'Satelite','México',7018665323);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Lucas','Hidalgo',90,68,'Napoles','Oaxaca',+247821131524);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia del Sol','Galeana',54,11,'Cuajimalpa','Baja California',0027789450);
INSERT INTO Sucursal(NombreSucursal,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Telefono) VALUES ('Farmacia San Miguel','Juárez',65,81,'Del Valle','Puebla',+322210547084);

--====================================================================================================
--                                  10 registros para Cliente
--====================================================================================================
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Nertie','Elnor','Utterson','2006-01-08','Carranza',30,89,'Bosques de Chapultepec','Baja California','Tarjeta');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Candy','Sketh','Baert','1949-12-28','Callejón del Beso',19,36,'La Paz','Durango','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Leland','Dovinson','McUre','2025-04-30','Gutiérrez',58,7,'Bosques de Chapultepec','Baja California','Tarjeta');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Eward','Braley','Simonite','1966-07-02','Morelos',33,80,'Los Pinos','Chiapas','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Erny','Rowler','Tures','1997-01-20','Carranza',44,2,'Valle Verde','Yucatán','Tarjeta');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Elspeth','Pooley','O''Bruen','1982-03-02','Calle de la Amargura',1,83,'Valle Verde','Chiapas','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Kevina','Casado','Albert','1972-11-27','Guerrero',93,1,'Santa Lucía','Aguascalientes','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Padraig','Broadist','Bielefeld','1951-10-28','Calle de la Amargura',48,23,'San Pedro','Tabasco','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Isaac','Alyonov','Reinbeck','2019-08-13','Calle de la Soledad',60,76,'La Paz','Tlaxcala','Efectivo');
INSERT INTO Cliente(Nombre,Paterno,Materno,FechaNacimiento,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,MetodoPago) VALUES ('Lynnea','Stocking','Siddaley','2018-05-31','Independencia',83,58,'Valle Verde','Tabasco','Efectivo');

--====================================================================================================
--                                  10 registros para Medico
--====================================================================================================
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('YDWV321202316','Leontyne','Goldthorp','Titterington','Callejón de la Condesa',90,84,'La Aurora','Sinaloa','Miercoles','23:06','07:06',61490.63,2,'Colegio de Médicos y Cirujanos','9/6/2024',1000001,'6/20/1999');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('PFUB761101FQ6','Idette','Bealton','Swinn','González',75,81,'Villa de las Flores','Baja California','Sabado','14:57','22:57',30099.63,5,'Instituto Nacional de Ciencias de la Salud','4/10/2023',1000002,'12/2/1998');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('IRQC461018365','Felicio','Hawkett','McQuillin','Morelos',56,12,'Las Palmas','Baja California','Jueves','6:05','14:05',19863.91,2,'Hospital Universitario de Medicina','3/1/2029',1000003,'7/13/1991');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('DWSD450408078','Aloise','Champneys','Tranckle','Carranza',66,25,'Santa Cruz','Querétaro','Sabado','13:07','21:07',32260.72,6,'Centro de Estudios Médicos Avanzados','2/7/2027',1000004,'8/2/1996');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('KFES640705YP8','Crysta','Spratley','Bourdel','Obregón',99,8,'Las Palmas','Durango','Domingo','8:18','16:18',24854.01,10,'Escuela Superior de Ciencias de la Salud','8/19/2026',1000005,'9/1/1996');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('MHYY920601195','Philipa','Guitte','Cunnington','Zaragoza',46,66,'Valle Verde','Oaxaca','Jueves','2:26','10:26',71894.1,3,'Instituto de Investigación Médica','9/22/2030',1000006,'4/5/1999');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('KRBZ750306M92','Arleen','Reding','Bilham','López Mateos',30,70,'Valle Verde','Baja California','Jueves','21:01','05:01',21738.08,3,'Escuela de Medicina y Ciencias de la Salud','5/7/2028',1000007,'10/24/1990');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('ENUT4610231V5','Kip','Croy','Welburn','Obregón',68,96,'Los Pinos','Aguascalientes','Jueves','13:43','21:43',62864.74,4,'Centro de Estudios Médicos Avanzados','8/28/2025',1000008,'4/26/1998');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('MBMO380825M20','Timoteo','Agg','Andreas','Allende',45,88,'San Miguel','Tamaulipas','Martes','20:51','04:51',43929.69,4,'Instituto de Salud Pública','4/21/2023',1000009,'2/5/1996');
INSERT INTO Medico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,InstitucionEgreso,VigenciaCertificacion,CedulaProfesional,FechaNacimiento) VALUES ('OXMJ631222BH4','Chere','Martino','Drysdale','Revolución',25,31,'San Pedro','Puebla','Domingo','15:21','23:21',71132.5,8,'Facultad de Medicina y Cirugía','2/6/2025',1000010,'10/30/2000');

--====================================================================================================
--                                  10 registros para Enfermero
--====================================================================================================
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('KDWS490405RC9','Jareb','Drage','Olanda','Benito Juárez',61,80,'El Rosario','El Rosario','Miercoles','16:13','00:13',45793.16,2,'Cambio de Vendajes','false',1000001,'9/23/1991');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('XLBF860620H76','Marabel','Gowers','Pawellek','López Mateos',20,100,'Los Pinos','Bosques de Chapultepec','Jueves','13:04','21:04',63757.72,7,'Cuidados Intensivos','true',1000002,'1/18/1995');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('XJCA211005B38','Lynnell','Parzis','Aizikowitz','Hidalgo',75,22,'Las Palmas','Bosques de Chapultepec','Domingo','2:54','10:54',60296.25,5,'Aplicación de Inyecciones','false',1000003,'2/5/1992');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('PFRA800627T69','Charleen','Gotch','Nock','Callejón del Beso',69,49,'La Primavera','Valle Verde','Domingo','10:13','18:13',58509.3,5,'Toma de Muestras de Sangre','true',1000004,'5/14/1998');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('VGMB840710277','Martguerita','Leppingwell','Kindon','Callejón del Beso',87,11,'Valle Verde','Santa Cruz','Lunes','18:05','02:05',84127.66,10,'Retiro de Sonda','false',1000005,'8/11/1994');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('SJUY321021EU7','Hedvige','Vernon','Mathelin','López Mateos',44,94,'Valle Verde','La Joya','Domingo','14:00','22:00',80719.89,8,'Atención Psiquiátrica','false',1000006,'8/4/1990');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('VIPU4907070U4','Tonya','Kairns','Cotty','Pino Suárez',18,28,'Las Palmas','Las Palmas','Martes','2:09','10:09',11306.94,5,'Curación de Heridas','true',1000007,'3/4/1998');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('FLGM240702R38','Nomi','Hechlin','Norgan','Morelos',36,17,'El Paraíso','Los Pinos','Martes','8:48','16:48',37340.01,5,'Control de Glucosa','false',1000008,'4/16/1992');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('KNJB701112J85','Vivi','Evequot','Gillan','Morelos',27,76,'La Primavera','Villa de las Flores','Jueves','6:11','14:11',36423.78,7,'Monitoreo de Pacientes','false',1000009,'6/18/1994');
INSERT INTO Enfermero(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,TipoProcedimientoCargo,CertificacionReanimacion,CedulaProfesional,FechaNacimiento) VALUES ('UTCN211112313','Alene','Fullerd','Chatwood','Carranza',89,44,'La Aurora','Los Pinos','Miercoles','13:34','21:34',29385.59,10,'Atención Pediátrica','true',1000010,'12/30/1991');


--====================================================================================================
--                                  8 registros para Ticket
--====================================================================================================
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-06-22','16:19','Presencial',1,6,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-01-19','2:26','Presencial',4,10,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-11-19','0:47','Presencial',8,6,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-01-15','9:00','Web',10,1,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-03-26','22:50','Web',3,10,TRUE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-09-08','10:26','Presencial',1,3,FALSE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2023-07-29','11:02','Web',8,1,FALSE,TRUE);
INSERT INTO Ticket(FechaPago,HoraPago,TipoVenta,IdSucursal,IdCliente,EsTicketConsulta,EsTicketMedicamento) VALUES ('2033-09-25','10:34','Presencial',7,5,FALSE,TRUE);

--====================================================================================================
--                                  5 registros para CobrarConsulta
--====================================================================================================
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2024-01-18','2:00','Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',825.18,6,'MBMO380825M20',NULL,1);
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2012-07-29','18:59','Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',1029.04,10,'PFUB761101FQ6',NULL,2);
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2014-06-20','6:37','Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',1235.0,6,'OXMJ631222BH4','SJUY321021EU7',3);
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2023-09-26','15:28','Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',595.7,1,'IRQC461018365','VGMB840710277',4);
INSERT INTO CobrarConsulta(Fecha,Hora,Diagnostico,Precio,IdCliente,RFCMedico,RFCEnfermero,FolioTicket) VALUES ('2012-06-01','19:48','Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',708.68,10,'IRQC461018365','PFRA800627T69',5);

--====================================================================================================
--                                  10 registros para Proveedor
--====================================================================================================
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Laboratorio Farmacéutico del Sur','Oriole',78,62,'San Francisco','New Mexico');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Distribuidora Salud S.A.','Mockingbird',11,62,'La Esperanza','Kansas');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Proveedor de Medicamentos Rápidos','Darwin',54,20,'El Rosario','Illinois');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Proveedor de Medicamentos Rápidos','Mifflin',45,93,'El Progreso','Illinois');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Farmacias del Pueblo','Lakewood',89,15,'San Antonio','Texas');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Farmacias del Pueblo','Caliangt',42,1,'El Progreso','Pennsylvania');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Distribuidora Salud S.A.','Gulseth',7,100,'San Miguel','California');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Proveedor de Medicamentos Rápidos','Northwestern',45,69,'Los Pinos','Kansas');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Farmacéutica Integral','Spaight',11,49,'Santa Rosa','Alabama');
INSERT INTO Proveedor(RazonSocial,Calle,NumeroExterior,NumeroInterior,Colonia,Estado) VALUES ('Suministros Farmacéuticos de Calidad','Erie',82,29,'El Rosario','Pennsylvania');

--====================================================================================================
--                                  10 registros para MedComercial
--====================================================================================================
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('Secret Clinical','Gel','40 mg/ml','Jeringa prellenada con 2ml de solución inyectable','Oral','Antibiótico','Genérico','Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.','Aluminum Zirconium Octachlorohydrex Gly','MediCo');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('CAPTOPRIL','Gel','35 mg/ml','Blister con 10 tabletas de 500mg','Oral','Analgésico','Veterinario','Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.','CAPTORPIL','BioPharm');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('SEROQUEL','Gel','20 mg/ml','Ampolla con 5ml de solución inyectable','Oral','Antidepresivo','Venta libre','Phasellus in felis. Donec semper sapien a libero. Nam dui.','Quetiapine fumarate','HealthCare Solutions');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('IMITREX','Gel','10 mg/ml','Tubo con 100g de crema dérmica','Oral','Expectorante','Experimental','Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.','sumatriptan succinate','VitaPharm');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('Black Birch','Gel','15 mg/ml','Blister con 10 tabletas de 500mg','Oral','Antibiótico','Naturista','Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.','Black Birch','Healix Laboratories');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('oxygen','Gel','20 mg/ml','Frasco con 30 cápsulas de 250mg','Oral','Vitaminas','Venta libre','Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.','oxygen','PharmaTech');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('Givenchy Photo Perfexion Fluid Foundation Broad Spectrum SPF 20 Perfect Cinnamon','Gel','30 mg/ml','Blister con 10 tabletas de 500mg','Oral','Analgésico','Venta libre','Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.','TITANIUM DIOXIDE, OCTINOXATE','PharmaLab');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('Isopropyl Alcohol','Gel','40 mg/ml','Frasco con 30 cápsulas de 250mg','Oral','Laxante','Marca registrada','In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.','Isopropyl Alcohol','Wellness Labs');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('Rifadin','Gel','50 mg/ml','Jeringa prellenada con 2ml de solución inyectable','Oral','Expectorante','Controlado','Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.','rifampin','HealthCare Solutions');
INSERT INTO MedComercial(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,NombreGenerico,LabFabricante) VALUES ('Citalopram','Gel','40 mg/ml','Sobre con 20 sobres de polvo para suspensión oral','Oral','Antidepresivo','Naturista','Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.','Citalopram','MediPro');

--====================================================================================================
--                                  10 registros para TenerMedComercial
--====================================================================================================
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (3,10,7,4763.44);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (4,4,9,523.32);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (8,1,2,2342.26);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (4,5,3,614.56);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (5,8,5,4151.04);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (7,7,5,4171.61);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (8,3,10,3394.38);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (3,7,1,2371.28);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (1,10,4,822.08);
-- INSERT INTO TenerMedComercial(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (2,10,10,2926.11);

--====================================================================================================
--                                  10 registros para MedPreparado
--====================================================================================================
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('Aminosyn','Gel','20 mg/ml','Sobre con 20 sobres de polvo suspensión oral','Oral','Vitaminas','Veterinario','Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.','Antialérgicos');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('NEXIUM','Gel','30 mg/ml','Sobre con 20 sobres de polvo suspensión oral','Oral','Vitaminas','Naturista','Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.','Antieméticos');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('Moxifloxacin','Gel','30 mg/ml','Envase 50 tabletas masticables 100mg','Oral','Antihistamínico','Genérico','Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','Antifúngicos');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('Fentanyl Citrate','Gel','50 mg/ml','Gotas oftálmicas en frasco de 15ml','Oral','Antiviral','Controlado','Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.','Analgésicos');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('METOCLOPRAMIDE','Gel','20 mg/ml','Envase con 60 comprimidos de lib prolongada','Oral','Vitaminas','No controlado','Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.','Antitusivos');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('Nifedipine','Gel','50 mg/ml','Envase con 60 comprimidos de lib prolongada','Oral','Antiviral','Receta médica','Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.','Analgésicos');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('Degree','Gel','30 mg/ml','Blister con 10 tabletas de 500mg','Oral','Vitaminas','Receta médica','In congue. Etiam justo. Etiam pretium iaculis justo.','Antivirales');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('GM Collin Mineral Sun Veil','Gel','5 mg/ml','Sobre con 20 sobres de polvo suspensión oral','Oral','Expectorante','Veterinario','Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.','Antiinflamatorios');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('BAROX','Gel','10 mg/ml','Envase con 60 comprimidos de lib prolongada','Oral','Antipirético','Controlado','Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.','Antipiréticos');
INSERT INTO MedPreparado(NombreComercial,FormaFarmaceutica,Concentracion,Presentacion,ViaAdministracion,Clasificacion,TipoControl,Descripcion,Categoria) VALUES ('Pollens - Trees, Mulberry Mix','Gel','45 mg/ml','Sobre con 20 sobres de polvo suspensión oral','Oral','Antihistamínico','Controlado','Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.','Antieméticos');

--====================================================================================================
--                                  10 registros para TenerMedPreparado
--====================================================================================================
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (4,6,8,3449.28);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (4,8,8,2387.32);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (1,3,7,3514.02);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (8,5,10,2979.64);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (7,7,5,4103.87);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (3,6,5,1267.74);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (1,4,1,1615.08);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (1,6,2,4122.62);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (6,2,5,931.64);
INSERT INTO TenerMedPreparado(FolioTicket,IdMedicamento,CantidadComprada,PrecioUnitario) VALUES (6,4,9,2225.51);

--====================================================================================================
--                                  10 registros para EntregarMedComercial
--====================================================================================================
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (5,7,2,'2025-11-30T02:52:26Z','2026-04-28','Mantener fuera del alcance de los niños',36,3671.67,472.57);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (9,2,10,'2025-11-20T19:55:37Z','2026-04-30','No exponer a temperaturas extremas',91,6139.38,3041.36);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (7,8,10,'2025-05-16T17:12:15Z','2026-04-21','Almacenar en un lugar fresco y seco',94,1152.89,2376.04);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (4,6,7,'2025-07-25T03:39:00Z','2026-05-02','Guardar en un recipiente hermético',51,7590.3,4030.87);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (8,8,4,'2025-12-18T20:45:25Z','2026-04-29','Proteger de la congelación',70,2123.59,1565.47);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (7,5,1,'2025-11-29T22:36:50Z','2026-04-22','Proteger de la congelación',65,5825.29,4161.06);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (3,10,2,'2025-08-09T18:11:04Z','2026-04-24','Mantener fuera del alcance de los niños',47,6280.77,6775.96);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (5,6,5,'2025-11-30T14:40:26Z','2026-05-02','Almacenar en un lugar bien ventilado',30,2265.95,2905.12);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (8,10,7,'2025-10-23T15:35:19Z','2026-04-29','Guardar en un lugar limpio y ordenado',73,3254.57,4992.21);
-- INSERT INTO EntregarMedComercial(IdProveedor,IdSucursal,IdMedicamento,FechaRecepcion,FechaCaducidad,CondicionesAlmacenamiento,CantidadRecibida,PrecioPublico,PrecioUnitario) VALUES (4,10,7,'2026-04-08T16:42:15Z','2026-04-27','Almacenar en un lugar bien ventilado',17,731.31,2055.14);

--====================================================================================================
--                                  10 registros para Farmaceutico
--====================================================================================================
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('FQEF490411JL3','Zolly','Easterby','Cribbins','Carranza',84,56,'Los Pinos','Hidalgo','Sabado','0:17','08:17',22053.62,4,2000001,'11/23/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('ALRH7712231X0','Renaud','Reiner','Bryenton','Juárez',36,85,'Villa de las Flores','Puebla','Lunes','16:35','00:35',16617.69,10,2000002,'11/16/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('HZMS180626U05','Roland','Linnett','Wickersham','González',31,81,'Valle Verde','Tamaulipas','Lunes','16:47','00:47',48649.11,2,2000003,'11/20/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('EZIM860818473','Elsworth','Glendzer','Monte','Callejón del Beso',88,14,'El Rosario','Puebla','Miercoles','19:21','03:21',5361.3,7,2000004,'11/18/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('AATE081208454','Alyosha','Di Giorgio','Ongin','Callejón de la Amargura',4,66,'San José','Hidalgo','Martes','4:12','12:12',36242.33,10,2000005,'11/11/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('TPKN0704117F9','Andrea','Mahaffey','True','Pino Suárez',27,5,'Bosques de Chapultepec','Guanajuato','Sabado','12:46','20:46',41701.33,8,2000006,'11/9/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('RROM830201YP7','Erny','Puncher','Mahaddy','Benito Juárez',70,77,'La Esperanza','Oaxaca','Domingo','10:36','18:36',41989.21,10,2000007,'11/26/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('KUZU671023UD2','Olivette','Northridge','Petrov','Callejón de la Amargura',43,21,'Los Pinos','Sinaloa','Lunes','22:05','06:05',5748.43,3,2000008,'11/16/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('OKSY2311023Y3','Jose','Edwick','Laidel','Carranza',6,35,'San José','Aguascalientes','Martes','2:32','10:32',41112.43,6,2000009,'11/22/2025');
INSERT INTO Farmaceutico(RFC,Nombre,Paterno,Materno,Calle,NumeroExterior,NumeroInterior,Colonia,Estado,Dia,Entrada,Salida,Salario,IdSucursal,CedulaProfesional,FechaNacimiento) VALUES ('VUNB2306100H2','Cecilla','Neylan','Sandeland','Obregón',64,16,'La Primavera','Querétaro','Sabado','7:02','15:02',20770.04,3,2000010,'11/12/2025');

--====================================================================================================
--                                  10 registros para Elaborar
--====================================================================================================
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('AATE081208454',3,'2020-07-28',16);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('FQEF490411JL3',4,'2022-03-23',19);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('OKSY2311023Y3',5,'2021-06-25',11);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('HZMS180626U05',2,'2022-06-21',3);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('HZMS180626U05',4,'2025-10-22',6);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('KUZU671023UD2',4,'2025-12-28',13);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('AATE081208454',6,'2022-07-14',10);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('KUZU671023UD2',5,'2026-02-16',7);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('AATE081208454',9,'2022-08-27',2);
INSERT INTO Elaborar(RFC,IdMedicamento,FechaElaboracion,CantidadElaborada) VALUES ('OKSY2311023Y3',1,'2022-12-03',19);

